//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LuaInterface_LuaFileUtilsWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(LuaInterface.LuaFileUtils), typeof(System.Object));
		L.RegFunction("Dispose", Dispose);
		L.RegFunction("AddSearchPath", AddSearchPath);
		L.RegFunction("RemoveSearchPath", RemoveSearchPath);
		L.RegFunction("GetPackagePath", GetPackagePath);
		L.RegFunction("AddSearchBundle", AddSearchBundle);
		L.RegFunction("FindFile", FindFile);
		L.RegFunction("ReadFile", ReadFile);
		L.RegFunction("FindFileError", FindFileError);
		L.RegFunction("GetOSDir", GetOSDir);
		L.RegFunction("New", _CreateLuaInterface_LuaFileUtils);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("beZip", get_beZip, set_beZip);
		L.RegVar("Instance", get_Instance, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateLuaInterface_LuaFileUtils(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				LuaInterface.LuaFileUtils obj = new LuaInterface.LuaFileUtils();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: LuaInterface.LuaFileUtils.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Dispose(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaInterface.LuaFileUtils obj = (LuaInterface.LuaFileUtils)ToLua.CheckObject(L, 1, typeof(LuaInterface.LuaFileUtils));
			obj.Dispose();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddSearchPath(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaInterface.LuaFileUtils obj = (LuaInterface.LuaFileUtils)ToLua.CheckObject(L, 1, typeof(LuaInterface.LuaFileUtils));
			string arg0 = ToLua.CheckString(L, 2);
			bool arg1 = LuaDLL.luaL_checkboolean(L, 3);
			bool o = obj.AddSearchPath(arg0, arg1);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveSearchPath(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaInterface.LuaFileUtils obj = (LuaInterface.LuaFileUtils)ToLua.CheckObject(L, 1, typeof(LuaInterface.LuaFileUtils));
			string arg0 = ToLua.CheckString(L, 2);
			bool o = obj.RemoveSearchPath(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetPackagePath(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaInterface.LuaFileUtils obj = (LuaInterface.LuaFileUtils)ToLua.CheckObject(L, 1, typeof(LuaInterface.LuaFileUtils));
			string o = obj.GetPackagePath();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddSearchBundle(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaInterface.LuaFileUtils obj = (LuaInterface.LuaFileUtils)ToLua.CheckObject(L, 1, typeof(LuaInterface.LuaFileUtils));
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.AssetBundle arg1 = (UnityEngine.AssetBundle)ToLua.CheckUnityObject(L, 3, typeof(UnityEngine.AssetBundle));
			obj.AddSearchBundle(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FindFile(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaInterface.LuaFileUtils obj = (LuaInterface.LuaFileUtils)ToLua.CheckObject(L, 1, typeof(LuaInterface.LuaFileUtils));
			string arg0 = ToLua.CheckString(L, 2);
			string o = obj.FindFile(arg0);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ReadFile(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaInterface.LuaFileUtils obj = (LuaInterface.LuaFileUtils)ToLua.CheckObject(L, 1, typeof(LuaInterface.LuaFileUtils));
			string arg0 = ToLua.CheckString(L, 2);
			byte[] o = obj.ReadFile(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FindFileError(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaInterface.LuaFileUtils obj = (LuaInterface.LuaFileUtils)ToLua.CheckObject(L, 1, typeof(LuaInterface.LuaFileUtils));
			string arg0 = ToLua.CheckString(L, 2);
			string o = obj.FindFileError(arg0);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetOSDir(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			string o = LuaInterface.LuaFileUtils.GetOSDir();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_beZip(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaInterface.LuaFileUtils obj = (LuaInterface.LuaFileUtils)o;
			bool ret = obj.beZip;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index beZip on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, LuaInterface.LuaFileUtils.Instance);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_beZip(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaInterface.LuaFileUtils obj = (LuaInterface.LuaFileUtils)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.beZip = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index beZip on a nil value" : e.Message);
		}
	}
}

